global_costmap:
   global_frame: wamv/odom
   robot_base_frame: wamv/base_link
   update_frequency: 2.0
   publish_frequency: 1.0
   static_map: false  
   rolling_window: true
   width: 20.0
   height: 20.0
   resolution: 0.05
   transform_tolerance: 0.5

  plugins:
   - {name: obstacle_layer_global,  type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}