shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 3.0


planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

max_planning_retries: 10

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "navfn/NavfnROS" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner

recovery_behaviors: [
        {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
        {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
        {name: rotate_recovery, type: rotate_recovery/RotateRecovery},        
        ]

conservative_clear:
    reset_distance: 1.0

aggressive_clear:
    reset_distance: 0.0

rotate_recovery:
    max_rotational_vel: 4.0
    min_in_place_rotational_vel: 3.0